routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin');
});

Route::get('/', function(){
    return view('student.create');
})->name('student.dashboard');

//Route::get('/student/show_grades',"StudentController@getGradesOfStudent")
//    ->name('student.show.grades');

Route::get('top', 'TopStudentsController')->name('top');


Route::get('/student',"StudentController@index")->name('student.index');
Route::post('student', 'StudentController@store')->name('student.store');
Route::delete('student/{student}', 'StudentController@delete')->name('student.destroy');



Route::get('student/{student}/grade/edit', "StudentGradeController@edit")->name('student.grade.edit');
Route::put('student/{student}/grade', "StudentGradeController@update")->name('student.grade.update');

Route::get('student/{student}/edit', "StudentController@edit")->name('student.edit');
Route::put('student/{student}', "StudentController@update")->name('student.update');

app/Grades.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Grades extends Model
{
    protected $guarded = [];

    protected $appends = ['average'];

    function getAverageAttribute()
    {
        return (($this->prelim + $this->midterm + $this->finals) / 3);
    }

    public function student()
    {
        return $this->belongsTo(Student::class);
    }
}

app/Student.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    protected $guarded = [];

    public static function boot()
    {
        static::created(function ($student) {
            $student->grade()->save(new Grades);
        });
    }

    public function getFullNameAttribute()
    {
        return $this->fname . ' ' . $this->lname;
    }

    public function getFormalNameAttribute()
    {
        return $this->lname . ', ' . $this->fname;
    }


    public function grade()
    {
        return $this->hasOne(Grades::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var a`rray
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Grades;
use App\Student;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use function redirect;

class StudentController extends Controller
{

    public function index()
    {
        return view('student.index', [
            'students' => Student::all()
        ]);
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'fname' => 'required',
            'lname' => 'required',
            'age' => 'required|integer',
            'yearlevel' => 'required|integer',
        ]);

        $student = Student::create($request->all(
            'fname', 'lname', 'age', 'yearlevel'
        ));

        return redirect()->route('student.index', $student);
    }


    public function edit(Student $student)
    {
        return view('student.edit',
            ["student" => $student]);
    }

    public function update(Request $request, Student $student)
    {
        static::update($request->only('prelim', 'midterm', 'finals'));
        return redirect()->route('student.index');

    }

    public function delete(Student $student)
    {

        $student->delete();

        return redirect()->back();
    }
}

app/Http/Controllers/StudentGradeController.php
<?php

namespace App\Http\Controllers;

use App\Student;
use App\Grades;
use Illuminate\Http\Request;

class StudentGradeController extends Controller
{

    public function edit(Student $student)
    {
        return view('grade.edit', [
            'student' => $student
        ]);
    }

    public function update(Request $request, Student $student)
    {
        $student->grade->update($request->only('prelim', 'midterm', 'finals'));

        return redirect()->route('top');

    }
}

app/Http/Controllers/TopStudentsController.php
<?php
/**
 * Created by PhpStorm.
 * User: eugenealvizo
 * Date: 13/07/2017
 * Time: 4:31 PM
 */

namespace App\Http\Controllers;

use App\Grades;

class TopStudentsController extends Controller
{
    function __invoke()
    {
        $grades = Grades::with('student')
            ->get()
            ->sortByDesc('average');

        return view('top ', [
            'grades'=> $grades
        ]);
    }

}

resources/views/admin.blade.php
<!doctype html>
<html lang="en">
<head>

    <style>
        table, th, td {
            border: 1px solid black;
            border-collapse: collapse;
        }
        th, td {
            padding: 15px;
            text-align: center;
            vertical-align: middle;
        }

    </style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>StudentBook</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{{route('student.dashboard')}}">StudentBook</a>
        </div>
        <div class="nav navbar-nav navbar-right">
            <li><a href="{{route('student.dashboard')}}">Home</a></li>
            <li><a href="{{route('student.index')}}">Students</a></li>
            <li><a href="{{route('top')}}">Top</a></li>
        </div>
    </div>
</nav>

<main>
    <div class="container">
        @yield('content')
    </div>
</main>

</body>
</html>

resources/views/grade/edit.blade.php
@extends('admin')

@section('content')
<form action="{{ route('student.grade.update', $student) }}" method="POST" class="form-horizontal">
    <input type="hidden" name="_method" value="PUT">

    {{--
    Laravel 5.4 Token Mismatch problem
    https://stackoverflow.com/questions/42687461/laravel-5-4-tokenmismatchexception-in-verifycsrftoken-php-line-68
    --}}
    {{ csrf_field() }}
    <div class="form-group">

        <h1>Updating Grades for {{ $student->lname }}, {{ $student->fname }}</h1>

        </br>
        </br>
        <label class="form-label" for="prelim">Prelim:</label>
        <input type="text" id="prelim" class="form-input" name="prelim" value="{{ $student->grade->prelim }}"
               placeholder="Prelim Grade"/>
        <p class="form-input-hint">{{ $errors->first('prelim') }}</p>

        <label class="form-label" for="midterm">Midterm:</label>
        <input type="text" id="midterm" class="form-input" name="midterm" value="{{ $student->grade->midterm }}"
               placeholder="Midterm"/>
        <p class="form-input-hint">{{ $errors->first('midterm') }} </p>

        <label class="form-label" for="finals">Finals:</label>
        <input type="text" id="finals" class="form-input" name="finals" value="{{ $student->grade->finals }}"
               placeholder="Final Grade"/>
        <p class="form-input-hint">{{ $errors->first('finals') }}</p>

        <button type="submit" class="btn btn-primary">Save</button>
    </div>
</form>
@stop

resources/views/student/create.blade.php
@extends('admin')

@section('content')

<form action="{{ route('student.store') }}" method="POST" class="form-horizontal">

    {{--
    Laravel 5.4 Token Mismatch problem
    https://stackoverflow.com/questions/42687461/laravel-5-4-tokenmismatchexception-in-verifycsrftoken-php-line-68
    --}}
    {{ csrf_field() }}
    <div class="form-group @haserror('first_name')">
        <label class="form-label" for="firstname">First Name:</label>
        <input type="text" id="firstname" class="form-input" name="fname" value="{{ old('fname') }}"
               placeholder="First Name"/>
        <p class="form-input-hint">{{ $errors->first('fname') }}</p>

        <label class="form-label" for="lastname">Last Name:</label>
        <input type="text" id="lastname" class="form-input" name="lname" value="{{ old('lname') }}"
               placeholder="Last Name"/>
        <p class="form-input-hint">{{ $errors->first('lname') }}</p>

        <label class="form-label" for="age">Age:</label>
        <input type="text" id="age" class="form-input" name="age" value="{{old('age')}}" placeholder="Age"/>
        <p class="form-input-hint">{{ $errors->first('age') }} </p>

        <label class="form-label" for="yearlevel">Year Level: </label>
        <input type="text" id="yearlevel" class="form-input" name="yearlevel" value="{{old('yearlevel')}}"
               placeholder="yearlevel"/>
        <p class="form-input-hint"> {{ $errors->first('yearlevel')}} </p>

        <button type="submit" class="btn btn-primary">Save</button>

    </div>
</form>

@stop

resources/views/student/edit.blade.php
@extends('admin')

@section('content')

    <form action="{{ route('student.edit', $student) }}" method="POST" class="form-horizontal">
        <input type="hidden" name="_method" value="PUT">
        {{--
        Laravel 5.4 Token Mismatch problem
        https://stackoverflow.com/questions/42687461/laravel-5-4-tokenmismatchexception-in-verifycsrftoken-php-line-68
        --}}
        {{ csrf_field() }}
        <div class="form-group @haserror('first_name')">

            <h1>Update Info for {{ $student->lname }}, {{ $student->fname }}</h1>

            <label class="form-label" for="firstname">First Name:</label>
            <input type="text" id="firstname" class="form-input" name="fname" value="{{ $student->fname }}"
                   placeholder="First Name"/>
            <p class="form-input-hint">{{ $errors->first('fname') }}</p>

            <label class="form-label" for="lastname">Last Name:</label>
            <input type="text" id="lastname" class="form-input" name="lname" value="{{ $student->lname }}"
                   placeholder="Last Name"/>
            <p class="form-input-hint">{{ $errors->first('lname') }}</p>

            <label class="form-label" for="age">Age:</label>
            <input type="text" id="age" class="form-input" name="age" value="{{$student->age}}" placeholder="Age"/>
            <p class="form-input-hint">{{ $errors->first('age') }} </p>

            <label class="form-label" for="yearlevel">Year Level: </label>
            <input type="text" id="yearlevel" class="form-input" name="yearlevel" value="{{$student->yearlevel}}"
                   placeholder="yearlevel"/>
            <p class="form-input-hint"> {{ $errors->first('yearlevel')}} </p>

            <button type="submit" class="btn btn-primary">Update</button>

        </div>
    </form>

@stop

resources/views/student/index.blade.php
@extends('admin')

@section('content')

    <table style="width:100%">
        <tr>
            <th>Firstname</th>
            <th></th>Lastname</th>
            <th>Age</th>
            <th>Year Level</th>
            <th>Action</th>
        </tr>
        @foreach($students as $student)
        <tr>
            <td>  {{ $student->fname }} </td>
            <td>  {{ $student->lname }} </td>
            <td>  {{ $student->age }} </td>
            <td>  {{ $student->yearlevel }}</td>
            <td>
                <a href="{{ route('student.grade.edit', $student) }}">Update Grades</a>
                <form method="POST" action="{{ route('student.destroy', $student) }}" >
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="DELETE">

                    <button>Delete</button>
                </form>

                <a href="{{route('student.edit', $student)}}")> Edit Student </a>
            </td>
        </tr>
        @endforeach

    </table>

@stop

resources/views/top.blade.php
@extends('admin')

@section('content')

    <table style="width:100%">
        <tr>
            <th>Student Name</th>
            <th>Year Level</th>
            <th>Average</th>
        </tr>

    @foreach($grades as $grade)
        <tr>
            <th>{{ $grade->student->formal_name }}</th>
            <th>{{ $grade->student->yearlevel }}</th>
            <th>{{ $grade->average }}</th>
        </tr>
    @endforeach
@stop